name: blade-test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - datasets==1.18.0
      - huggingface-hub==0.2.1
      - numpy==1.22.1
      - sentencepiece
      - tokenizers
      - torch
      - torchaudio
      - torchvision
      - tqdm
      - transformers
